#!/bin/sh
set -e
PATH="/usr/local/bin:${PATH}"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=-sql
mv .git/tags.$$ .git/tags

#mkdir .git/tags_lock 2>/dev/null || exit 0
#trap "rmdir .git/tags_lock; rm .git/tags.$$" EXIT
#ctags --tag-relative -R -f .git/tags.$$ --exclude=.git --languages=-sql,-css
#mv .git/tags.$$ .git/tags
